"""Add amount_input and exchange_rate to receipt and expense models

Revision ID: f7b04679bfec
Revises: 20260625_add_soft_delete_to_copper_cassiterite_outputs
Create Date: 2026-06-05 10:58:09.007288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7b04679bfec'
down_revision = '20260625_add_soft_delete_to_copper_cassiterite_outputs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_input', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('supplier_payment_receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_input', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('worker_payment_receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_input', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_payment_receipt', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('amount_input')

    with op.batch_alter_table('supplier_payment_receipt', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('amount_input')

    with op.batch_alter_table('expense_transaction', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('amount_input')

    # ### end Alembic commands ###
